check:
  - thoth-build
build:
  base-image: "quay.io/odh-jupyterhub/jupyterhub:v3.5.3"
  build-stratergy: "Source"
  registry: "quay.io"
  registry-org: "modh"
  registry-project: "jupyterhub-img"
  registry-secret: "modh-pusher-secret"
